import streamlit as st
from generators.plantuml_gen import DIAGRAM_REGISTRY
from generators import analysis
from utils.plantuml_renderer import render_to_bytesio
from utils.parallel import run_parallel
from core import rag_engine
import config
from ui.utils import _save_file

def _render_one(name_puml):
    name, puml = name_puml
    return name, render_to_bytesio(puml)

def render():
    """Renders the UML Diagrams tab."""
    st.markdown("## 📐 UML Diagrams")
    st.caption(
        "Generate 8 types of UML diagrams using RAG + LLM. "
        "Select a single diagram or use **Batch Generate** to create "
        "multiple diagrams in parallel with threading."
    )

    stats = rag_engine.get_project_stats()
    diagram_names = list(DIAGRAM_REGISTRY.keys())
    class_names = analysis.get_class_list(stats)

    # ── Single diagram generation ──
    st.markdown("### 🎯 Single Diagram")
    col_sel, col_focus = st.columns([1, 1])
    with col_sel:
        selected_diagram = st.selectbox(
            "Diagram Type:",
            diagram_names,
            key="uml_type_select",
        )
    with col_focus:
        gen_func, needs_focus = DIAGRAM_REGISTRY[selected_diagram]
        if needs_focus:
            focus_sel = st.selectbox(
                "Focus on class (optional):",
                ["(All Classes)"] + class_names,
                key="uml_focus_class",
            )
        else:
            focus_sel = None
            st.info(f"ℹ️ {selected_diagram} does not use a focus class.")

    if st.button("🎨 Generate Diagram", key="gen_single_uml"):
        with st.spinner(f"Generating {selected_diagram} via RAG + LLM…"):
            if needs_focus and focus_sel and focus_sel != "(All Classes)":
                puml = gen_func(focus_sel)
            elif needs_focus:
                puml = gen_func(None)
            else:
                puml = gen_func()

        # Store in session state so data survives Streamlit reruns
        st.session_state["last_puml"] = puml
        st.session_state["last_diagram_name"] = selected_diagram

        with st.spinner("Rendering diagram image…"):
            img = render_to_bytesio(puml)
        if img:
            st.session_state["last_png"] = img.getvalue()  # store raw bytes
        else:
            st.session_state["last_png"] = None

    # ── Display results from session state (persists across reruns) ──
    if "last_puml" in st.session_state and st.session_state["last_puml"]:
        puml = st.session_state["last_puml"]
        diagram_name = st.session_state.get("last_diagram_name", "Diagram")
        png_bytes = st.session_state.get("last_png")
        safe_name = diagram_name.lower().replace(" ", "_")

        st.markdown(f"### 📊 {diagram_name}")
        if png_bytes:
            st.image(png_bytes, caption=diagram_name, use_container_width=True)

            # Download buttons — save directly to Downloads folder
            dl_col1, dl_col2, dl_col3 = st.columns(3)
            with dl_col1:
                if st.button("🖼️ Save as PNG", key="save_png"):
                    path = _save_file(png_bytes, f"{safe_name}.png")
                    st.success(f"✅ Saved to `{path}`")
            with dl_col2:
                if st.button("📷 Save as JPG", key="save_jpg"):
                    from PIL import Image
                    from io import BytesIO
                    img = Image.open(BytesIO(png_bytes)).convert("RGB")
                    jpg_buf = BytesIO()
                    img.save(jpg_buf, format="JPEG", quality=95)
                    path = _save_file(jpg_buf.getvalue(), f"{safe_name}.jpg")
                    st.success(f"✅ Saved to `{path}`")
            with dl_col3:
                if st.button("💾 Save .puml", key="save_puml"):
                    path = _save_file(puml, f"{safe_name}.puml")
                    st.success(f"✅ Saved to `{path}`")
        else:
            st.error(
                "⚠️ Could not render the diagram image. The PlantUML syntax "
                "generated by the LLM may contain errors. Check the source "
                "below and try regenerating."
            )

        with st.expander(
            "📝 View PlantUML Source Code",
            expanded=not bool(png_bytes),
        ):
            st.code(puml, language="plantuml")

    # ── Batch diagram generation (parallel) ──
    st.markdown('<div class="section-divider"></div>', unsafe_allow_html=True)
    st.markdown("### ⚡ Batch Generate (Parallel)")
    st.caption(
        f"Generate multiple diagrams concurrently using "
        f"**{config.PARALLEL_MAX_WORKERS} worker threads**."
    )

    batch_selected = st.multiselect(
        "Select diagrams to generate:",
        diagram_names,
        default=["Class Diagram", "Component Diagram", "Use Case Diagram"],
        key="batch_select",
    )

    if st.button("🚀 Batch Generate", key="gen_batch_uml",
                 disabled=len(batch_selected) == 0):
        progress = st.progress(0, text="Starting batch generation…")

        step_count = [0]
        total_steps = len(batch_selected)

        def _batch_progress(msg):
            step_count[0] += 1
            progress.progress(
                min(step_count[0] / total_steps, 1.0),
                text=msg,
            )

        # Build tasks — for batch, we skip focus class (use project-wide)
        tasks = []
        for name in batch_selected:
            gen_func, needs_focus = DIAGRAM_REGISTRY[name]
            if needs_focus:
                tasks.append((name, lambda f=gen_func: f(None)))
            else:
                tasks.append((name, gen_func))

        with st.spinner(f"Generating {len(tasks)} diagrams in parallel…"):
            results = run_parallel(
                tasks,
                max_workers=config.PARALLEL_MAX_WORKERS,
                progress_callback=_batch_progress,
            )

        progress.progress(1.0, text="✅ All diagrams generated!")

        # Pre-render all diagrams in parallel (faster than sequential HTTP)
        from concurrent.futures import ThreadPoolExecutor
        
        render_pairs = [(n, results[n]) for n in batch_selected if results.get(n)]
        with st.spinner(f"Rendering {len(render_pairs)} diagrams…"):
            with ThreadPoolExecutor(max_workers=4) as pool:
                rendered = dict(pool.map(_render_one, render_pairs))

        # Display each result
        for name in batch_selected:
            puml = results.get(name, "")
            if not puml:
                continue
            st.markdown(f'<div class="diagram-card"><h4>📐 {name}</h4></div>',
                        unsafe_allow_html=True)

            img = rendered.get(name)
            if img:
                st.image(img, caption=name, use_container_width=True)
                img.seek(0)
                safe_name = name.lower().replace(" ", "_")
                st.download_button(
                    f"🖼️ Download {name} PNG", img.read(),
                    file_name=f"{safe_name}.png",
                    mime="image/png", key=f"dl_batch_{safe_name}_png",
                )
            else:
                st.error(
                    f"⚠️ Could not render {name}. The LLM-generated PlantUML "
                    f"may have syntax issues. See source below."
                )

            with st.expander(f"📝 {name} — PlantUML Source", expanded=False):
                st.code(puml, language="plantuml")
